### ISSUE TITLE
timezone

### ISSUE THREAD

**Issue by ikoctya** [rosteleset/SmartYard-Server#14]
/opt/rbt/server/hw/domophones/is/is.php строка 260, временная зона не из конфигурации
/opt/rbt/server/hw/domophones/beward/dks/dks.php строка 300, временная зона не из конфигурации
/opt/rbt/server/hw/domophones/beward/ds/ds.php строка 167, временная зона не из конфигурации
/opt/rbt/server/hw/domophones/hikvision/hikvision.php строка 283,  временная зона не из конфигурации
/opt/rbt/server/hw/domophones/qtech/qdb/qdb.php строка 433,  временная зона не из конфигурации
/opt/rbt/server/hw/domophones/rubetek/rubetek.php строка 213,   временная зона не из конфигурации

**Comment by subs1stem** [comment]
[В этой ветке](https://github.com/rosteleset/SmartYard-Server/tree/feature/smart_autoconfig) ведется работа над таймзонами в том числе. Для большинства панелей уже реализовано.

**Comment by ikoctya** [comment]
отлично. а как часто изменения оттуда переносятся в основную? Видел, что при обновлении основной, некоторые обновления форсированно загружаются из нее

**Comment by subs1stem** [comment]
Ветка еще не вливалась в main, но практически каждый день обновляется из main

**Comment by ikoctya** [comment]
получается сегодня зона уже в основной ветке для бевардов и соколов берется из конфига?

**Comment by subs1stem** [comment]
> получается сегодня зона уже в основной ветке для бевардов и соколов берется из конфига?

Верно. Для домофонов берется из адреса по иерархии от города до региона. Если нигде не указана - будет использована таймзона сервера. Для камер из поля "Часовой пояс" в камере. Если не указана - таймзона сервера.
