### ISSUE TITLE
Forpost error handling

### ISSUE THREAD

**Issue by ikoctya** [rosteleset/SmartYard-Server#15]
При получении скриншота с медиа-сервера Forpost не учтена возможная ошибка (например при не совпадении временной зоны сервера и камеры или при отсутствии записи по каким-то причинам):
/opt/rbt/server/backends/dvr/internal/internal.php строка 471
в результате чего события plog открытия двери отрабатывают тоже с ошибками, новые события не появляются.

_forpost api:
POST-URL: /system-api/GetTranslationURL
Вслучае ошибки параметр содержит код ошибки:
● 1 - неизвестная ошибка
● 2 - ошибка валидации параметров вызова
● 3 - доступ запрещен_

**Comment by alexeimenshikh** [comment]
В plog добавили проверку URL для скриншота и события должны создаваться в случае проблем с его получением.
