### ISSUE TITLE
Уведомление о событиях через push

### ISSUE THREAD

**Issue by temandroid** [rosteleset/SmartYard-Server#79]
Можно ли реализовать возможность подключения уведомлений о событии, причем выборочную, например, если кто-то с твоим ключем или кодом зашел в подъезд, прилетал пуш на подписанные устройства. Сейчас все пишется в plog и больше ничего не вызывается, а абоненты спрашивают о такой функции. Ну или я не нашел :)

**Comment by subs1stem** [comment]
По этому поводу есть [обсуждение](https://github.com/rosteleset/SmartYard-Server/discussions/33). Предлагаю переместиться туда
